language: python
python:
- "3.6"
script:
- python3 kml_generator.py


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  keep-history: true
  on:
    branch: master
